### ISSUE TITLE
Bug report as issue. --- discussion on templates

### ISSUE THREAD

**Issue by OlaShabalina** [CodeforAustralia/council-emissions-calculator#213]
I'm submitting a bug report.

## What is the current behaviour?
> Explain what the issue is including screenshots and/or links. What did you do to get this issue?

## What is the expected behaviour?
> What is supposed to happen when the bug is fixed?

## Do you know what cause the issue? If yes, can you list or briefly explain.
> Explain the cause of the issue

## Solution (or options to fix the bug)

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

[Link to Trello card](link)

**Comment by OlaShabalina** [comment]
Just to sum @Amutha37 's comments:
- remove `I'm submitting a bug report` part for the issue;
- replace: `Please provide the steps to reproduce and if possible a minimal demo of the problem` with `Do you know what cause the issue? If yes, can you list or briefly explain.`;

**Comment by OlaShabalina** [comment]
> The line 1 heading font size looks smaller to all the sub questions. Title need to be a bit outstanding I feel.

Like this?
![image](https://user-images.githubusercontent.com/88268603/198824253-d5e06c4a-bab1-4c4f-9e92-6c10850ed4c1.png)
Or you want this like to be removed completely?

**Comment by hqtan** [comment]
This issue has been resolved by PR #226
