### ISSUE TITLE
Fix alignment for all components(sections) on the results page

### ISSUE THREAD

**Issue by OlaShabalina** [CodeforAustralia/council-emissions-calculator#216]
## I'm submitting a ...

- bug report

## What is the current behavior?

Sections have different alignment (example - first section is center aligned, top three - is left aligned, etc);

![image](https://user-images.githubusercontent.com/88268603/199363127-24313569-c064-4edb-b462-6acd09af6181.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

* Open browser and go to https://council-emissions-calculator-spike-flax.vercel.app/results
* Open toggle device toolbar and choose mobile

## What is the expected behavior?

- [ ] each section is center aligned 
- [ ] each section has the same margins and padding from both sides.

## Solution

Change alignment for the section to be consistent of mobile.

## What is the motivation / use case for changing the behavior?

Responsiveness on mobile.

**Link to Trello card:** [here](https://trello.com/c/hqw5CLOC)

**Comment by OlaShabalina** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[DEV]: Fix results page mobile layout to make it responsive](https://trello.com/c/hqw5CLOC/16-dev-fix-results-page-mobile-layout-to-make-it-responsive)

**Comment by Amutha37** [comment]
Looks like most of the components  are fitting well into mobile responsive. Well done Qing ..
Just for one  component graph .

This is now ...
![Screenshot 2023-03-07 at 10 59 53 am](https://user-images.githubusercontent.com/67087939/223286036-fd9f823e-8c4a-42d6-80b7-f2b749ffa881.png)

This is before ....

![Screenshot 2023-03-07 at 11 03 38 am](https://user-images.githubusercontent.com/67087939/223286101-57d44cec-fd32-4fa3-a43a-a6ae063ada45.png)

Is this something for different PR.
