### ISSUE TITLE
Add link back to home page to SeeChange logo

### ISSUE THREAD

**Issue by OlaShabalina** [CodeforAustralia/council-emissions-calculator#224]
I'm submitting a feature request.

## What feature do you recommend to add?

**SeeChange** logo on top of the page should lead back to the home page for a smooth User experience: 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/88268603/199362254-5432dfc0-876f-4f71-bef5-b1da0849b973.png">

## What is the value of this feature?

Users can come back to the main page at any moment. There is a perception that clicking on the logo returns the user to the home page.

## Solution

- [ ] Logo is a link that returns the user to the Home page: `/` locally or `https://council-emissions-calculator-spike-flax.vercel.app/` for staging and `http://seechange.codeforaustralia.org/` for production.

[Link to Trello card](https://trello.com/c/n5RPlQI6)

**Comment by lestercorreya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[DEV]: Add link back to home page to SeeChange logo](https://trello.com/c/n5RPlQI6/26-dev-add-link-back-to-home-page-to-seechange-logo)

**Comment by Amutha37** [comment]
This is great . Well done Lester.

**Comment by lestercorreya** [comment]
> This is great . Well done Lester.

Thank you :)
