### ISSUE TITLE
Feature request as issue. --- discussion on templates

### ISSUE THREAD

**Issue by OlaShabalina** [CodeforAustralia/council-emissions-calculator#225]
I'm submitting a feature request.

## What feature do you recommend to add?
> New design/functionality or modification of existing feature

## What is the value of this feature?
> How it will improve the current view/behaviour 

## What are the approx. steps to create this feature? 

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

[Link to Trello card](https://trello.com/c/n5RPlQI6)

**Comment by OlaShabalina** [comment]
Sounds great Qing, feel free to modify the issue as per what you mentioned. 👍🏻

**Comment by hqtan** [comment]
The issue templates have been approved and merged, so this issue has been resolved.

Feel free to re-open this issue if resume discussions.
